---
# These tasks are to install Satellite through the CLI including answer files.

## TODO: Need to work on a new answer file
#- name: install_satellite | Copy satellite answer file
#  template:
#    src: satellite-answers.yaml
#    dest: /etc/foreman-installer/scenarios.d/satellite-answers.yaml
#  tags:
#  - install_satellite

# - name: Load Satellite answer file varriables
#   include_vars:
#     file: ../vars/answer-file.yml
#
# - name: install_satellite | Verify Foreman exists
#   stat:
#     path: /etc/init.d/foreman
#   register: foreman_location
#   tags:
#     - install_satellite

# - name: Copy satellite answers file to target
#   copy:
#     src: ../templates/satellite-answers.yaml
#     dest: /etc/foreman-installer/scenarios.d/satellite-answers.yaml
#   when: foreman_location.stat.exists
#   tags:
#     - install_satellite
- name: SATELLITE | configure satellite | Load Satellite answer file varriables
  include_vars: file=vars/answer-file.yml

- name: SATELLITE | deploy_satellite | Create satellite answers file
  template:
    src: satellite-answers.j2
    dest: /etc/foreman-installer/scenarios.d/satellite-answers.yaml
    owner: root
    group: root
    mode: 0644

- name: SATELLITE | deploy_satellite | Install Satellite with desired scenario
  command: /usr/sbin/satellite-installer --scenario "{{ satellite_scenario }}"
  tags:
    - install_satellite
