---
- name: SATELLITE | firewall | Install Firewalld
  yum:
    name: firewalld
    state: present
  tags:
    - firewalld

- name: SATELLITE | firewall | Enable and Start Firewalld
  service:
    name: firewalld
    enabled: yes
    state: started
  tags:
    - firewalld

- name: SATELLITE | firewall | Enable ports in firewall
  firewalld:
    port: "{{ item }}"
    permanent: yes
    state: enabled
  with_items:
    - "{{ firewall_ports }}"
  tags:
    - firewalld

- name: SATELLITE | firewall | Enable service in firewall
  firewalld:
    service: "{{ item }}"
    permanent: yes
    state: enabled
  with_items:
    - "{{ firewall_services }}"
  tags:
    - firewalld
