- name: SATELLITE | provision satellite | Create Satellite vg_data lvm volume group
  lvg:
    vg: "{{ satellite_volgrp }}"
    pvs: "{{ satellite_data_physvol }}"
    force: no

- name: SATELLITE | provision satellite | Create Satellite lvm logical volumes
  lvol:
    lv: "{{ item.lvname }}"
    vg: "{{ satellite_volgrp }}"
    size: "{{ item.lvsize }}"
    state: present
  with_items: "{{ satellite_volumes }}"

- name: SATELLITE | provision satellite | Format Satellite logical volumes
  filesystem:
    fstype: xfs
    dev: /dev/{{ satellite_volgrp }}/{{ item.lvname }}
  with_items: "{{ satellite_volumes }}"

- name: SATELLITE | provision satellite | Add Satelite data volumes to fstab
  mount:
    name: "{{ item.mtpoint }}"
    src: "{{ item.lvpath }}"
    fstype: xfs
    state: mounted
  with_items: "{{ satellite_volumes }}"
