---
# tasks file for satellite6-install
- include: registration.yml
  when: rhn_registration

- include: format_volumes.yml
  when: satellite_format_volumes

- include: firewall.yml

- include: install_software.yml

- include: deploy_satellite.yml
